/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.poryecto_competencias2.vistas;

import com.mycompany.poryecto_competencias2.vistas.VistaEmpleadosAtrasados;
import com.mycompany.poryecto_competencias2.Controlador.ControladorUsuarios;
import com.mycompany.poryecto_competencias2.DAOs.usuariosDAO;
import com.mycompany.poryecto_competencias2.modelos.Login;
import com.mycompany.poryecto_competencias2.modelos.usuarios;

import com.mycompany.poryecto_competencias2.Controlador.Conexion;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.mycompany.poryecto_competencias2.Controlador.ControladorReportesDAO;
import com.mycompany.poryecto_competencias2.modelos.ReporteAtrasoModelo;

import java.io.FileOutputStream;
import java.sql.Date;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;




/**
 *
 * @author marti
 */
public class VistaMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuAdmin
     */
    public VistaMenuAdmin() {
        initComponents();
        cargarTablaEmpleados();
    }
    
    public ControladorUsuarios controladorusuario = new ControladorUsuarios();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel jPanelReal = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        tfContrasena = new javax.swing.JTextField();
        javax.swing.JButton btnAnadir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfRut = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfCorreoElectronico = new javax.swing.JTextField();
        javax.swing.JButton btnEliminar = new javax.swing.JButton();
        javax.swing.JButton btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnVistaEmpleadosAtrasados = new javax.swing.JButton();
        btnVistaEmpleadosAtrasados2 = new javax.swing.JButton();
        btnVistaEmpleadosAtrasados1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Empleados");

        jPanelReal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Emoji", 0, 12))); // NOI18N
        jPanelReal.setOpaque(false);

        jLabel2.setText("Nombres");

        tfNombre.setForeground(new java.awt.Color(204, 204, 204));
        tfNombre.setText("Ingrese nombre del empleado");
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Contraseña");

        tfContrasena.setForeground(new java.awt.Color(204, 204, 204));
        tfContrasena.setText("Ingrese una contraseña");

        btnAnadir.setText("Añadir Empleado");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        jLabel4.setText("Apellidos");

        tfApellidos.setForeground(new java.awt.Color(204, 204, 204));
        tfApellidos.setText("Ingrese los apellidos");

        jLabel5.setText("Teléfono");

        tfTelefono.setForeground(new java.awt.Color(204, 204, 204));
        tfTelefono.setText("Ingrese un número de teléfono");

        jLabel6.setText("Rut");

        tfRut.setForeground(new java.awt.Color(204, 204, 204));
        tfRut.setText("Ingrese el rut sin puntos ni guíon");
        tfRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRutActionPerformed(evt);
            }
        });

        jLabel7.setText("Dirección");

        tfDireccion.setForeground(new java.awt.Color(204, 204, 204));
        tfDireccion.setText("Ingrese la dirección del empleado");

        jLabel8.setText("Correo Electronico");

        tfCorreoElectronico.setForeground(new java.awt.Color(204, 204, 204));
        tfCorreoElectronico.setText("Ingrese un correo electronico");
        tfCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCorreoElectronicoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Empleado");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRealLayout = new javax.swing.GroupLayout(jPanelReal);
        jPanelReal.setLayout(jPanelRealLayout);
        jPanelRealLayout.setHorizontalGroup(
            jPanelRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfNombre)
            .addComponent(tfApellidos)
            .addComponent(tfContrasena, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(tfTelefono)
            .addComponent(tfRut)
            .addGroup(jPanelRealLayout.createSequentialGroup()
                .addComponent(btnAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2)
            .addComponent(jLabel4)
            .addComponent(jLabel5)
            .addComponent(jLabel3)
            .addComponent(jLabel6)
            .addComponent(jLabel7)
            .addComponent(jLabel8)
            .addComponent(tfCorreoElectronico)
            .addComponent(tfDireccion)
            .addGroup(jPanelRealLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRealLayout.setVerticalGroup(
            jPanelRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRealLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(tfCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Telefono", "Rut", "Dirección", "Email", "Contraseña"
            }
        ));
        jScrollPane1.setViewportView(tablaEmpleados);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reportes"));
        jPanel1.setToolTipText("");
        jPanel1.setOpaque(false);

        btnVistaEmpleadosAtrasados.setText("Visualizar empleados atrasados");
        btnVistaEmpleadosAtrasados.setBorder(new javax.swing.border.MatteBorder(null));
        btnVistaEmpleadosAtrasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaEmpleadosAtrasadosActionPerformed(evt);
            }
        });

        btnVistaEmpleadosAtrasados2.setText("Visualizar empleados inasistentes");
        btnVistaEmpleadosAtrasados2.setBorder(new javax.swing.border.MatteBorder(null));
        btnVistaEmpleadosAtrasados2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaEmpleadosAtrasados2ActionPerformed(evt);
            }
        });

        btnVistaEmpleadosAtrasados1.setText("Visualizar empleados salida antes");
        btnVistaEmpleadosAtrasados1.setBorder(new javax.swing.border.MatteBorder(null));
        btnVistaEmpleadosAtrasados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaEmpleadosAtrasados1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVistaEmpleadosAtrasados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVistaEmpleadosAtrasados1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVistaEmpleadosAtrasados2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVistaEmpleadosAtrasados, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVistaEmpleadosAtrasados1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVistaEmpleadosAtrasados2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnVistaEmpleadosAtrasados.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelReal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jPanelReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Reportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
                                          
   
    String nombre = tfNombre.getText().trim();
    String apellido = tfApellidos.getText().trim();
    String telefono = tfTelefono.getText().trim();
    String rut = tfRut.getText().trim();
    String direccion = tfDireccion.getText().trim();
    String correo = tfCorreoElectronico.getText().trim();
    String contra = tfContrasena.getText().trim();

    if (nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty() ||
        rut.isEmpty() || direccion.isEmpty() || correo.isEmpty() || contra.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese todos los campos",
                "Intente de nuevo", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        
        usuarios u = new usuarios(nombre, apellido, telefono, rut, direccion, correo, contra);

     
        Login l = new Login(0, 0, correo, contra);

      
        controladorusuario.registrarUsuario(u, l);

      
        DefaultTableModel modelo = (DefaultTableModel) tablaEmpleados.getModel();
        modelo.addRow(new Object[]{ nombre, apellido, telefono, rut, direccion, correo });
        tablaEmpleados.setModel(modelo);

       
        JOptionPane.showMessageDialog(this, "Empleado agregado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        tfNombre.setText("");
        tfApellidos.setText("");
        tfTelefono.setText("");
        tfRut.setText("");
        tfDireccion.setText("");
        tfCorreoElectronico.setText("");
        tfContrasena.setText("");
        

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al registrar empleado: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }

    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        tfNombre.setText("");
        tfApellidos.setText("");
        tfTelefono.setText("");
        tfRut.setText("");
        tfDireccion.setText("");
        tfCorreoElectronico.setText("");
        tfContrasena.setText("");
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
                                           
    int filaSeleccionada = tablaEmpleados.getSelectedRow();

    if(filaSeleccionada == -1){
        JOptionPane.showMessageDialog(this, "Seleccione un empleado de la tabla",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

  
    int idEmpleado = Integer.parseInt(tablaEmpleados.getValueAt(filaSeleccionada, 0).toString());

   
    int opcion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea eliminar a este empleado?", 
            "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

    if(opcion == JOptionPane.YES_OPTION){
        try {
           
            usuariosDAO dao = new usuariosDAO();
            dao.eliminarUsuario(idEmpleado);

          
            DefaultTableModel modelo = (DefaultTableModel) tablaEmpleados.getModel();
            modelo.removeRow(filaSeleccionada);

            JOptionPane.showMessageDialog(this, "Empleado eliminado correctamente",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar empleado: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void btnVistaEmpleadosAtrasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaEmpleadosAtrasadosActionPerformed

   
    VistaEmpleadosAtrasados vistaAtrasados = new VistaEmpleadosAtrasados();
    
 
    vistaAtrasados.setVisible(true);
    
  
    vistaAtrasados.setLocationRelativeTo(null);

    this.dispose();

    }//GEN-LAST:event_btnVistaEmpleadosAtrasadosActionPerformed

    private void tfRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRutActionPerformed

    private void tfCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCorreoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCorreoElectronicoActionPerformed

    private void btnVistaEmpleadosAtrasados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaEmpleadosAtrasados1ActionPerformed
     VistaEmpleadosSalidaAntes vistaSalida = new VistaEmpleadosSalidaAntes();
    
 
    vistaSalida.setVisible(true);
    
  
    vistaSalida.setLocationRelativeTo(null);

    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnVistaEmpleadosAtrasados1ActionPerformed

    private void btnVistaEmpleadosAtrasados2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaEmpleadosAtrasados2ActionPerformed
    VistaEmpleadosInasistentes vistaInasistente = new VistaEmpleadosInasistentes();
    
 
    vistaInasistente.setVisible(true);
    
  
    vistaInasistente.setLocationRelativeTo(null);

    this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_btnVistaEmpleadosAtrasados2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuAdmin().setVisible(true);
            }
        });
    }
    
private void cargarTablaEmpleados() {
    DefaultTableModel model = (DefaultTableModel) tablaEmpleados.getModel();
    model.setRowCount(0); 

    ControladorUsuarios controlador = new ControladorUsuarios();

    Login l = null;

    ArrayList<usuarios> users = controlador.buscarUsuario(l);
    
    for(usuarios u: users){

        model.addRow(new Object[]{
            u.getNombre(),
            u.getApellidos(),
            u.getTelefono(),
            u.getRut(),
            u.getDireccion()
        });
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVistaEmpleadosAtrasados;
    private javax.swing.JButton btnVistaEmpleadosAtrasados1;
    private javax.swing.JButton btnVistaEmpleadosAtrasados2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfContrasena;
    private javax.swing.JTextField tfCorreoElectronico;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfRut;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
